# JAX numpy basics

In [11]:
import jax.numpy as jnp

## Array Initialization

In [12]:
jnp.array([1, 2, 3])

Array([1, 2, 3], dtype=int32)

In [13]:
jnp.zeros((3, 4)), jnp.ones((3, 4)), jnp.full((3, 4), 5), jnp.empty((3, 4))

(Array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32),
 Array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32),
 Array([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]], dtype=int32, weak_type=True),
 Array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32))

In [14]:
jnp.arange(10), jnp.linspace(0, 1, 10), jnp.eye(3)

(Array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 Array([0.        , 0.11111111, 0.22222222, 0.33333334, 0.44444445,
        0.5555556 , 0.6666667 , 0.7777778 , 0.8888889 , 1.        ],      dtype=float32),
 Array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32))

## Shape Properties and Operations

In [15]:
i = jnp.array([[1, 2, 3], [4, 5, 6]])
print(i.shape)
print(i.reshape((1, 6)))
print(i.flatten())
print(jnp.transpose(i))
print(i.T)
print(jnp.squeeze(i))
print(jnp.expand_dims(i, axis=0))

(2, 3)
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]


## Array Operations

In [16]:
x = jnp.array([1.0, 2.0, 3.0])
y = jnp.array([4.0, 5.0, 6.0])

print(x + y)           # add
print(x * y)           # multiply
print(x ** 2)          # power
print(jnp.sqrt(x))     # sqrt
print(jnp.abs(-x))     # abs
print(jnp.exp(x))      # exp
print(jnp.log(x))      # log
print(jnp.dot(x, y))   # dot
A = jnp.array([[1.0, 2.0], [3.0, 4.0]])
B = jnp.array([[5.0, 6.0], [7.0, 8.0]])
print(jnp.matmul(A, B))  # matmul

[5. 7. 9.]
[ 4. 10. 18.]
[1. 4. 9.]
[1.        1.4142135 1.7320508]
[1. 2. 3.]
[ 2.7182817  7.389056  20.085537 ]
[0.        0.6931472 1.0986123]
32.0
[[19. 22.]
 [43. 50.]]


## Aggregation Operations

In [17]:
j = jnp.array([[1, 2, 3], [4, 5, 6]])

print(jnp.sum(j))
print(jnp.mean(j))
print(jnp.max(j))
print(jnp.min(j))
print(jnp.std(j))
print(jnp.var(j))
print(jnp.argmax(j))
print(jnp.argmin(j))
print(jnp.cumsum(j))

21
3.5
6
1
1.7078252
2.9166667
5
0
[ 1  3  6 10 15 21]


## Indexing and Slicing

In [18]:
k = jnp.arange(12).reshape((3, 4))
print(k)
print(k[0])        # first row
print(k[:, 1])     # second column
print(k[1:, 2:])   # submatrix
print(k[0, -1])    # last element of first row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[1 5 9]
[[ 6  7]
 [10 11]]
3


## Trigonometric Functions

In [19]:
angles = jnp.linspace(0, jnp.pi, 5)
print(jnp.sin(angles))
print(jnp.cos(angles))
print(jnp.tan(angles))

[ 0.0000000e+00  7.0710677e-01  1.0000000e+00  7.0710677e-01
 -8.7422777e-08]
[ 1.0000000e+00  7.0710677e-01 -4.3711388e-08 -7.0710677e-01
 -1.0000000e+00]
[ 0.0000000e+00  1.0000000e+00 -2.2877334e+07 -1.0000000e+00
  8.7422777e-08]


## Linear Algebra

In [20]:
M = jnp.array([[1.0, 2.0], [3.0, 4.0]])

print(jnp.linalg.inv(M))       # inv
print(jnp.linalg.det(M))       # det
print(jnp.linalg.norm(M))      # norm
print(jnp.linalg.eig(M))       # eig (eigenvalues, eigenvectors)
U, S, Vt = jnp.linalg.svd(M)
print(U, S, Vt)                 # svd

[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]
-2.0
5.477226
EigResult(eigenvalues=Array([-0.37228107+0.j,  5.3722816 +0.j], dtype=complex64), eigenvectors=Array([[-0.8245648 +0.j, -0.41597357+0.j],
       [ 0.56576747+0.j, -0.9093767 +0.j]], dtype=complex64))
[[-0.40455365 -0.91451436]
 [-0.9145144   0.4045536 ]] [5.4649854 0.3659661] [[-0.5760485  -0.81741554]
 [ 0.81741554 -0.5760485 ]]
